/**
 * Shared types for project templates.
 */

/**
 * Content generated by a template.
 */
export interface TemplateContent {
  /** Cargo.toml file content */
  cargoToml: string;
  /** src/main.rs file content */
  mainRs: string;
  /** .env.example file content */
  envExample: string;
  /** README.md file content */
  readme: string;
}

/**
 * Metadata about a template.
 */
export interface TemplateMetadata {
  /** Template identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Description of what the template creates */
  description: string;
  /** Required API keys for this template */
  requiredApiKeys: string[];
  /** ADK crates used by this template */
  adkCrates: string[];
}
